# Generated by Django 4.2.2 on 2023-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=30)),
                ('pnombre', models.CharField(max_length=30)),
            ],
        ),
    ]
